name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  JobOne:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1"
  JobTwo:
    runs-on: ubuntu-latest
    needs: JobOne
    steps:
      - run: echo "Job 2"
